version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # RabbitMQ management port
      - "5672:5672" # RabbitMQ main port
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 5

  blockchain-listener:
    build:
      context: .
      dockerfile: ./blockchain-listener/Dockerfile
    ports:
      - "8081:8081"
      - "50051:50051" # gRPC port
    networks:
      - microservices-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    ports:
      - "8082:8082"
      - "50052:50052" # gRPC port
    networks:
      - microservices-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  relayer-service:
    build:
      context: .
      dockerfile: ./relayer-service/Dockerfile
    ports:
      - "8083:8083"
      - "50053:50053" # gRPC port
    networks:
      - microservices-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  common-service:
    build:
      context: .
      dockerfile: ./common-service/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
