// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deposit struct {
	ID              int32
	ContractAddress pgtype.Text
	Commitment      pgtype.Text
	Depositor       pgtype.Text
	LeafIndex       pgtype.Int4
	TxHash          pgtype.Text
	Timestamp       pgtype.Numeric
	BlockNumber     pgtype.Int4
	ChainID         pgtype.Int4
}

type KycInfo struct {
	CitizenID     string
	FullName      pgtype.Text
	PhoneNumber   pgtype.Text
	DateOfBirth   pgtype.Date
	Nationality   pgtype.Text
	Verifier      pgtype.Text
	IsActive      pgtype.Bool
	KycVerifiedAt pgtype.Timestamp
}

type WalletInfo struct {
	WalletAddress   string
	CitizenID       pgtype.Text
	WalletSignature pgtype.Text
	CreatedAt       pgtype.Timestamp
}

type Withdrawal struct {
	ID              int32
	ContractAddress pgtype.Text
	Recipient       pgtype.Text
	NullifierHash   pgtype.Text
	Relayer         pgtype.Text
	Fee             pgtype.Numeric
	TxHash          pgtype.Text
	Timestamp       pgtype.Numeric
	BlockNumber     pgtype.Int4
	ChainID         pgtype.Int4
}
