// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateKycInfo(ctx context.Context, arg CreateKycInfoParams) (KycInfo, error)
	CreateWalletInfo(ctx context.Context, arg CreateWalletInfoParams) (WalletInfo, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error)
	GetAllWithdrawalsOfContract(ctx context.Context, contractAddress pgtype.Text) ([]Withdrawal, error)
	GetAllWithdrawalsOfRecipient(ctx context.Context, recipient pgtype.Text) ([]Withdrawal, error)
	GetDepositsFromBlockToBlock(ctx context.Context, arg GetDepositsFromBlockToBlockParams) ([]Deposit, error)
	GetKycInfoByCitizenID(ctx context.Context, citizenID string) (KycInfo, error)
	GetKycInfoByWalletAddress(ctx context.Context, walletAddress string) (KycInfo, error)
	GetLatestWithdrawalSyncedBlockOfContractOnChain(ctx context.Context, arg GetLatestWithdrawalSyncedBlockOfContractOnChainParams) (interface{}, error)
	UpdateKycInfo(ctx context.Context, arg UpdateKycInfoParams) (KycInfo, error)
	GetDepositByCommitment(ctx context.Context, commitment pgtype.Text) (Deposit, error)
	GetWithdrawalByNullifierHash(ctx context.Context, nullifierHash pgtype.Text) (Withdrawal, error)
}

var _ Querier = (*Queries)(nil)
